/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sem2Tester.java
 *
 * Created on Jan 18, 2010, 8:21:05 PM
 */

package Seminarska;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author zidar
 */
public class Sem2Tester extends javax.swing.JFrame {
    private int rows;
    private int cols;
    private int faktor;
    private int[] zaporedje;
    private MyTable myTable;
    private MyDraw draw;
    private PRTree prTree;
    private KDTree kdTree;
    private int stDimenzij;
    private double[] vector;
    /** Creates new form Sem2Tester */
    public Sem2Tester() {
        rows =0;
        cols =0;
        faktor =0;
        stDimenzij = 2;
        int[] azaporedje = {0,1};
        zaporedje = azaporedje;

        initComponents();
        draw = new MyDraw(jPanel1.getGraphics());

        draw.setHeight(jPanel1.getHeight()-20);
        draw.setWidth(jPanel1.getWidth());
        draw.setKoordinate(jCheckBox1.isSelected());

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jColsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRowsTextField = new javax.swing.JTextField();
        generateRandomTableButton = new javax.swing.JButton();
        prBuildTimeLabel = new javax.swing.JLabel();
        kdBuildTimeLabel = new javax.swing.JLabel();
        rBuildTimeLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        readFileButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        narisiTockeButton = new javax.swing.JButton();
        narisiVektorButton = new javax.swing.JButton();
        narisiTockeButton1 = new javax.swing.JButton();
        stNajblizjihTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vectorLabel = new javax.swing.JLabel();
        readVectorButton = new javax.swing.JButton();
        randomVectorButton = new javax.swing.JButton();
        vectorLenghtTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        jColsTextField.setText("5");

        jLabel1.setText("vrstice");

        jLabel2.setText("stoplci");

        jRowsTextField.setText("30");

        generateRandomTableButton.setText("generatRandom");
        generateRandomTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRandomTableButtonActionPerformed(evt);
            }
        });

        prBuildTimeLabel.setText("gradnja pr drevesa");

        kdBuildTimeLabel.setText("gradnja kd drevesa");

        rBuildTimeLabel.setText("gradnja r drevesa");

        fileNameTextField.setText("/home/zidar/vreme1e3.csv");

        readFileButton.setText("readFile");
        readFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prBuildTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(kdBuildTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(rBuildTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jColsTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateRandomTableButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRowsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateRandomTableButton))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jColsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prBuildTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kdBuildTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBuildTimeLabel))
        );

        jLabel5.setText("timeout");

        jTextField2.setText("0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.setText("600");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("faktor");

        jCheckBox1.setText("koordinate");

        narisiTockeButton.setText("narisi");
        narisiTockeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narisiTockeButtonActionPerformed(evt);
            }
        });

        narisiVektorButton.setText("najblizje");
        narisiVektorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narisiVektorButtonActionPerformed(evt);
            }
        });

        narisiTockeButton1.setText("vektor");
        narisiTockeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narisiTockeButton1ActionPerformed(evt);
            }
        });

        stNajblizjihTextField.setText("3");

        jLabel6.setText("st najblizjih");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(narisiTockeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                            .addComponent(stNajblizjihTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(narisiVektorButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                            .addComponent(narisiTockeButton1))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(narisiTockeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(narisiTockeButton1)
                    .addComponent(narisiVektorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stNajblizjihTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField3.setText("jTextField3");

        jLabel4.setText("vektor");

        vectorLabel.setText("jLabel6");

        readVectorButton.setText("preberi vektor");

        randomVectorButton.setText("random vektor");
        randomVectorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomVectorButtonActionPerformed(evt);
            }
        });

        vectorLenghtTextField.setText("5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vectorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vectorLenghtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randomVectorButton)
                            .addComponent(readVectorButton))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(readVectorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomVectorButton)
                    .addComponent(jLabel4)
                    .addComponent(vectorLenghtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vectorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void narisiTockeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narisiTockeButtonActionPerformed
        // TODO add your handling code here:
        int timout =0;
        try {
            timout = Integer.parseInt(jTextField2.getText());
            Graphics g = jPanel1.getGraphics();
            g.setColor(Color.white);
            g.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());

            draw.setHeight(jPanel1.getHeight()-20);
            draw.setWidth(jPanel1.getWidth());
            draw.setKoordinate(jCheckBox1.isSelected());
            draw.setFaktor(faktor);

            draw.drawTable(g, myTable.getTab());
            prTree.drawTree(draw,timout);
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_narisiTockeButtonActionPerformed

    private void generateRandomTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRandomTableButtonActionPerformed
        // TODO add your handling code here:
        try{
            cols = Integer.parseInt(jColsTextField.getText());
            rows = Integer.parseInt(jRowsTextField.getText());
            faktor = Integer.parseInt(jTextField1.getText());
            double[][] tempTab = TabFun.makeRandomTable(rows, cols);
            TabFun.normalizerajCols(tempTab);
            double[][] t = tempTab.clone();
            
            myTable = new MyTable(t);

            timer.startTimer();
            prTree = new PRTree(myTable, zaporedje, stDimenzij);
            prBuildTimeLabel.setText(timer.returnTimer("gradnja PR drevesa : ", 1)+" sekund");

            t = tempTab.clone();
            timer.startTimer();
            kdTree = new KDTree(tempTab, zaporedje, stDimenzij);
            kdBuildTimeLabel.setText(timer.returnTimer("gradnja KD drevesa : ", 1)+" sekund");
        }catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_generateRandomTableButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void readFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFileButtonActionPerformed
        // TODO add your handling code here:
        try{
            faktor = Integer.parseInt(jTextField1.getText());
            draw.setFaktor(faktor);
            double[][] tempTab = MyFileReader.readFileScanner(fileNameTextField.getText());
            TabFun.normalizerajCols(tempTab);
            double[][] t = tempTab.clone();
            jRowsTextField.setText(""+t.length);
            jColsTextField.setText(""+t[0].length);
            myTable = new MyTable(t);

            timer.startTimer();
            prTree = new PRTree(myTable, zaporedje, stDimenzij);
            prBuildTimeLabel.setText(timer.returnTimer("gradnja PR drevesa : ", 1)+" sekund");

            t = tempTab.clone();
            timer.startTimer();
            kdTree = new KDTree(tempTab, zaporedje, stDimenzij);
            kdBuildTimeLabel.setText(timer.returnTimer("gradnja KD drevesa : ", 1)+" sekund");
        }catch (Exception e){
            System.out.println("branje: "+e.toString());
        }
    }//GEN-LAST:event_readFileButtonActionPerformed

    private void randomVectorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomVectorButtonActionPerformed
        // TODO add your handling code here:
        int vl = 10;
        try {
            vl = Integer.parseInt(vectorLenghtTextField.getText());
        } catch (Exception e) {
        }
        vector= TabFun.makeRandomTable(1, vl)[0];
        vectorLabel.setText(getVektorString(vector));
    }//GEN-LAST:event_randomVectorButtonActionPerformed

    private void narisiVektorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narisiVektorButtonActionPerformed
        // TODO add your handling code here:
        int stNajblizjih = 2;
        if (this.vector == null){
            vectorLabel.setText("neveljavni vektor");
            return;
        }
        try {
            stNajblizjih = Integer.parseInt(stNajblizjihTextField.getText());
            faktor = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException numberFormatException) {
        }
        draw.setFaktor(faktor);
        draw.drawVectorPoint(vector);
        prTree.drawIsciNajblizjeBox(vector, stNajblizjih);
    }//GEN-LAST:event_narisiVektorButtonActionPerformed

    private void narisiTockeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narisiTockeButton1ActionPerformed
        // TODO add your handling code here:
        if (this.vector == null){
            vectorLabel.setText("neveljavni vektor");
            return;
        }
        try {
            faktor = Integer.parseInt(jTextField1.getText());
        } catch (NumberFormatException numberFormatException) {
        }
        draw.setFaktor(faktor);
        draw.drawVectorPoint(vector);
        prTree.drawIsciNajblizjeTrivial(vector, stDimenzij);
    }//GEN-LAST:event_narisiTockeButton1ActionPerformed

    private String getVektorString(double[] vektor){
        String s = new String("");
        for (int i=0; i<vektor.length; i++){
            s+=("        ".substring(((""+vektor[i]+"         ").substring(0, 5)).length())+(""+vektor[i]+"              ").substring(0, 5));
        }
        return s;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sem2Tester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JButton generateRandomTableButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextField jColsTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jRowsTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel kdBuildTimeLabel;
    private javax.swing.JButton narisiTockeButton;
    private javax.swing.JButton narisiTockeButton1;
    private javax.swing.JButton narisiVektorButton;
    private javax.swing.JLabel prBuildTimeLabel;
    private javax.swing.JLabel rBuildTimeLabel;
    private javax.swing.JButton randomVectorButton;
    private javax.swing.JButton readFileButton;
    private javax.swing.JButton readVectorButton;
    private javax.swing.JTextField stNajblizjihTextField;
    private javax.swing.JLabel vectorLabel;
    private javax.swing.JTextField vectorLenghtTextField;
    // End of variables declaration//GEN-END:variables

}
